### ISSUE TITLE
Consider making a variant with built-in error correction

### ISSUE THREAD

**Issue by tsbockman** [MaiaVictor/DesuHex#3]
While the pronunciation guide can easily be made clear and unambiguous, that still leaves two problems:

1) Not all sounds exist/are distinguished in all languages. Even with a guide, some people will simply be incapable of correctly pronouncing and distinguishing certain sounds.

2) Ordinary users will certainly not be willing to study a pronunciation guide, even if they have the right linguistic background.

There is no way of *completely* solving either of these issues, but a variant of Bitspeak could be developed that is usable for a far wider audience through the use of an error correcting code. The mapping of bit patterns to sounds, and the error correcting code itself, should be designed to minimize the impact of common errors in pronunciation and listening comprehension in the target language group(s).

(Unlike my other two suggestions, this would take a significant effort to get right, and complicate the technical design. So, feel free to just close this as out of project scope.)

**Comment by VictorTaelin** [comment]
I'm not a fan of error correction for the same reason I'm not a fan of JavaScript implicit casts. I'd rather just have the parser throw a good error message when it sees something like `c` than to make an attempt of fixing an incorrect input.

**Comment by tsbockman** [comment]
OK. I'll close this one then.
