### ISSUE TITLE
Pad 6-bit Bitspeak at the end

### ISSUE THREAD

**Issue by aadnk** [MaiaVictor/DesuHex#5]
I've started writing a Java port of Bitspeak (see [aadnk/Bitspeak4j](https://github.com/aadnk/Bitspeak4j)), but I hit a bit of a snag in implementing the 6 bit-version (or BS-6). The specification doesn't state how to handle an array of bytes that cannot be evenly split into chunks of 6 bits (such as byte arrays of length 1, 4, 7, 10, etc.), so I had to look at your implementation for clues.

The implementation seems to handle this by adding zeroes at the beginning of the bit array (converted from a byte array) until the number of bits are divisible by 6, effectively right-shifting every byte by `6 - bits.length % 6` and moving the shifted bits to the next byte. This works, but it is has the unfortunate side-effect of being hard to implement for a streaming API (like `InputStream`/`Reader` in Java), where you don't know the total number of bytes in advance. This is often the case when dealing with data from a socket, or a heavy computation from a worker/thread. I suggest you copy the padding mechanism in Base64 (which is also 6-bit), and pad with zero bits at the end rather than the beginning. Then you simply discard those extra bits in the decoder. 

For instance, when encoding AB in BS-6 (1010 1011), you convert 1010 to "l", 10 to "i", leaving "11". Since we need a consonant, we pad with zeroes - yielding "1100", or "m". This produces the string "lim". Then during decoding, you convert "l" to "1010", "i" to "10" and "m" to "1100", producing the bits 1010 1011 00. The two extra zero bits at the end can be safely discarded.

Granted, supporting a streaming API is a bit overkill for this use-case, but considering that there's no real advantage to breaking the mold and zero padding at the start, I'd rather pad with zeroes at the end. 

More examples:

Input | BS-6, padding at the start | BS-6, padding at the end 
--- | --- | ---
AB | pile | lim 
ABAB | tirile | lisir 
ABABAB | lisirile | lisirile 
ABABABAB | pilelisirile | lisirilelim 
ABABABABAB | tirilelisirile | lisirilelisir 

## Whitespace/delimiters
Finally, it would be nice if the specification allowed for whitespace/URL-safe characters to appear in Bitspeak, so you could divide the characters up into words and lines. Consider _"nelinizisemabapipam"_ (BS-6) - it's much more readable as _"nelini-zisema-bapi_pam"_. You could let the encoder configure the word length (like a maximum of 6 characters per word, 120 characters per line, etc.), and simply ignore these characters in the decoder.

**Comment by VictorTaelin** [comment]
Makes sense, I'm fine with that, but someone would need to submit a PR for this repository to be compliant, I can't do it right now.

**Comment by aadnk** [comment]
No problem, I'll see if I can't submit a simple PR for this issue.

Incidentally, decided to rename my Java-implementation to Bitspeak4j, to avoid any confusion with your JavaScript implementation.

**Comment by VictorTaelin** [comment]
Thanks!
